# General Settings
name: İlkay Narlı
job_title: Senior Software Developer
email: ilkaynarli@gmail.com
description: I am software developing since 2007.
avatar: /assets/img/inarli.jpg
favicon: /favicon.ico
twitter_handler: inarli
analytics_code: UA-160013990-1
disqus: inarli.disqus.com

# Social Accounts
social_networks:
-  { name: facebook, url: '' }
-  { name: twitter, url: 'https://twitter.com/inarli' }
-  { name: instagram, url: '' }
-  { name: google-plus, url: '' }
-  { name: linkedin, url: 'https://www.linkedin.com/in/inarli/' }
-  { name: skype, url: 'skype:inarli?call' }
-  { name: github, url: 'https://www.github.com/inarli' }
-  { name: codepen, url: '' }
-  { name: stack-overflow, url: '' }
-  { name: dribbble, url: '' }
-  { name: behance, url: '' }
-  { name: pinterest, url: '' }
-  { name: tumblr, url: '' }
-  { name: youtube, url: '' }
-  { name: vimeo, url: '' }
-  { name: vine, url: '' }
-  { name: 500px, url: '' }
-  { name: flickr, url: '' }
-  { name: spotify, url: '' }
-  { name: steam, url: '' }
-  { name: wordpress, url: '' }
-  { name: xing, url: '' }
-  { name: bitcoin, url: '' }
-  { name: pocket, url: '' }
-  { name: applemusic, url: '' }

# Modules Settings
show_categories: 1
show_tags: 1
show_email: 1
show_rss: 1
show_comments: 1
show_menu: 0
fixed_sidebar: 0

# Defaults
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      comments: "true"

# Serving
url: "https://www.inarli.com"
baseurl: "https://www.inarli.com"

# Includes
include: ["_pages"]

# Outputting
permalink: /:categories/:title.html
category_dir: categories

# Pagination
paginate: 10
paginate_path: "/page:num/"

# Conversion
markdown: kramdown
excerpt_separator: <!--more-->

# Assets Settings
sass:
  sass_dir: assets/partials
  style: compressed

